#!/bin/sh

# This script is for cleaning platform depencies of the specified architecture

##########################################################################################################################################
##  Board evkmimx8mp
##########################################################################################################################################

script_path=$(dirname $(realpath "$0"))
if [ -z "$1" ]; then
    echo "usage: "$0" <sdk.tar.gz>"
    exit 1
fi

mkdir -p "${script_path}"/tmp 
tar -xzf "$1" -C "${script_path}"/tmp

cp -r "${script_path}"/tmp/boards/evkmimx8mp/ "${script_path}"/../sdk/boards
cp -r "${script_path}"/tmp/devices/MIMX8ML8/ "${script_path}"/../sdk/devices

rm -rf "${script_path}"/tmp

grep -rl "MIMX8ML8)" "${script_path}"/../sdk/boards/evkmimx8mp/ | xargs sed -i 's/_MIMX8ML8//g'
find "${script_path}"/../sdk/ -name "config.cmake" | xargs grep "MIMX8ML8" -rl | xargs sed -i 's/_MIMX8ML8//g'

##########################################################################################################################################
##  Device MIMX8ML8
##########################################################################################################################################

find "${script_path}"/../sdk/devices/MIMX8ML8/ ! -path "*gcc*"  -type f -name "*MIMX8ML8*" | xargs rename.ul "_MIMX8ML8" ""
grep  -rl --exclude-dir="gcc" "MIMX8ML8)" "${script_path}"/../sdk/devices/MIMX8ML8/ | xargs sed -i 's/_MIMX8ML8//g'
find "${script_path}"/../sdk/devices/MIMX8ML8/   -maxdepth 1 -type f -name "*MIMX8ML8*" | xargs rename.ul "_MIMX8ML8" ""
grep -rl "system_MIMX8ML8_cm7.h" "${script_path}"/../sdk/devices/MIMX8ML8/ | xargs sed -i 's/system_MIMX8ML8_cm7.h/system_cm7.h/g'
find "${script_path}"/../sdk/devices/MIMX8ML8/ -name "*startup*"  | xargs rename.ul "_MIMX8ML8" ""